/**
 * @fileoverview Patient agent. Stationary — occupies a bed and never moves.
 * Responsible for need generation (stochastic, seeded), health tracking,
 * and critical incident detection.
 */
import Agent from './Agent.js';

export default class Patient extends Agent {
  /**
   * @param {object} params
   * @param {string|number} params.id
   * @param {{x: number, y: number}} params.position - Bed cell coordinates (fixed)
   * @param {import('./Grid.js').default} params.grid
   * @param {import('../config.js').CONFIG} params.config
   * @param {import('./NeedQueue.js').default} params.needQueue
   * @param {import('./SeededRandom.js').default} params.rng
   */
  constructor({ id, position, grid, config, needQueue, rng }) {
    super({ id, position, grid });
    this.config = config;
    this.needQueue = needQueue;
    this.rng = rng;

    this.health = config.HEALTH_MAX;
    /** @type {object[]} References to active (unfulfilled) needs in the queue */
    this.activeNeeds = [];
    /** @type {object[]} All needs ever generated by this patient */
    this.needsHistory = [];
    /** @type {number} Running count of critical incidents for this patient */
    this.criticalIncidents = 0;

    // Patients are always "in bed" — no state machine
    this.state = 'IN_BED';
  }

  /**
   * Roll for new need generation. Called during tick step 1.
   * @param {number} currentTick
   */
  generateNeeds(currentTick) {
    const needTypes = ['emergency', 'medication', 'comfort', 'visitor_escort'];

    for (const type of needTypes) {
      // Cannot have two of the same need type active simultaneously
      if (this.needQueue.hasActiveNeedOfType(this.id, type)) continue;

      const spawnRate = this.config.NEED_SPAWN_RATE[type];
      if (this.rng.random() < spawnRate) {
        const need = this.needQueue.postNeed({
          type,
          patientId: this.id,
          position: { ...this.position },
          urgencyWeight: this.config.URGENCY_WEIGHT[type],
          createdAtTick: currentTick,
        });
        this.activeNeeds.push(need);
        this.needsHistory.push(need);
      }
    }
  }

  /**
   * Apply health drain for each active unfulfilled need.
   * Called during tick step 7.
   * Detects critical incidents (health ≤ 0) and resets health.
   * @param {number} currentTick
   * @returns {boolean} True if a critical incident occurred this tick
   */
  drainHealth() {
    // Re-sync activeNeeds with what is still not fulfilled in the queue
    this.activeNeeds = this.activeNeeds.filter(n => n.status !== 'fulfilled');

    for (const need of this.activeNeeds) {
      this.health -= this.config.HEALTH_DRAIN_PER_TICK[need.type];
    }

    // Clamp to 0 before the critical check — health must never persist below 0
    if (this.health < 0) this.health = 0;

    if (this.health <= 0) {
      this.health = this.config.HEALTH_CRITICAL_RESET;
      this.criticalIncidents++;
      return true;
    }

    return false;
  }

  /**
   * Recover health when a need is fulfilled.
   * Called during tick step 6.
   * @param {string} _needType - The type of need that was fulfilled (unused here, for symmetry)
   */
  recoverHealth(_needType) {
    this.health = Math.min(
      this.config.HEALTH_MAX,
      this.health + this.config.HEALTH_RECOVERY_PER_NEED
    );
    // Remove the fulfilled need from activeNeeds
    this.activeNeeds = this.activeNeeds.filter(n => n.status !== 'fulfilled');
  }
}
